### ISSUE TITLE
Error when submitting a document for signature : Unexpected token '<'

### ISSUE THREAD

**Issue by maoo** [OpenSignLabs/OpenSign#146]
I'm trying to run OpenSign locally using Docker compose; when I hit the `Submit` button, either under `Sign Yourself` or `Request Signatures`, I hit the error attached below.

I reproduced the same error on `v1.0.2` tag and `staging` branch.

I've followed installation instructions, and updated the following variables in my `.env` file (starting from `.env.frontend_dev`):
- DO_SPACE
- DO_ENDPOINT
- DO_BASEURL
- DO_ACCESS_KEY_ID
- DO_SECRET_ACCESS_KEY
- DO_REGION
- PFX_BASE64

Anyone have stumbled on this already?

Attaching logs below.

### On screen
```
ERROR : Unexpected token '<'
Cannot read properties of undefined (reading '__initialized')
TypeError: Cannot read properties of undefined (reading '__initialized')
    at http://localhost:3000/static/js/node_modules_mf-cra_dist_index_js-_1dba0.chunk.js:109:33
    at Generator.next (<anonymous>)
    at http://localhost:3000/static/js/node_modules_mf-cra_dist_index_js-_1dba0.chunk.js:90:67
    at new Promise (<anonymous>)
    at __awaiter (http://localhost:3000/static/js/node_modules_mf-cra_dist_index_js-_1dba0.chunk.js:72:10)
    at HTMLScriptElement.<anonymous> (http://localhost:3000/static/js/node_modules_mf-cra_dist_index_js-_1dba0.chunk.js:106:44)
```

### On container logs
```
OpenSignServer-container  | new entry is insert in contracts_Document
OpenSignServer-container  | info: afterSave triggered for contracts_Document for user Fa5iA4nN6b:
OpenSignServer-container  |   Input: {"ACL":{"Fa5iA4nN6b":{"read":true,"write":true},"*":{"read":true,"write":true}},"ExtUserPtr":{"__type":"Pointer","className":"contracts_Users","objectId":"PJbvhSBP7G"},"CreatedBy":{"__type":"Pointer","className":"_User","objectId":"Fa5iA4nN6b"},"URL":"http://127.0.0.1:8080/app/files/opensignstgn/6ee3f92c93d4c44c47a44e7f38547fac_Cartell_EsmorzArt.pdf","Name":"sdfdsf","createdAt":"2023-11-06T19:49:27.300Z","IsCompleted":false,"IsDeclined":false,"SendinOrder":false,"RemindOnceInEvery":5,"AutomaticReminders":false,"SentToOthers":false,"TimeToCompleteDays":15,"updatedAt":"2023-11-06T19:49:27.300Z","objectId":"GrYY3YINBR"} {"className":"contracts_Document","triggerType":"afterSave","user":"Fa5iA4nN6b"}
OpenSignServer-container  | info: afterSave triggered for contracts_Document for user undefined:
OpenSignServer-container  |   Input: {"ExtUserPtr":{"__type":"Pointer","className":"contracts_Users","objectId":"PJbvhSBP7G"},"CreatedBy":{"__type":"Pointer","className":"_User","objectId":"Fa5iA4nN6b"},"URL":"http://127.0.0.1:8080/app/files/opensignstgn/6ee3f92c93d4c44c47a44e7f38547fac_Cartell_EsmorzArt.pdf","Name":"sdfdsf","IsCompleted":false,"IsDeclined":false,"SendinOrder":false,"RemindOnceInEvery":5,"AutomaticReminders":false,"SentToOthers":false,"TimeToCompleteDays":15,"createdAt":"2023-11-06T19:49:27.300Z","updatedAt":"2023-11-06T19:49:27.341Z","ACL":{"Fa5iA4nN6b":{"read":true,"write":true},"*":{"read":true,"write":true}},"ExpiryDate":{"__type":"Date","iso":"2023-11-21T19:49:27.300Z"},"objectId":"GrYY3YINBR"} {"className":"contracts_Document","triggerType":"afterSave"}
OpenSignServer-container  | info: afterSave triggered for contracts_Document for user undefined:
OpenSignServer-container  |   Input: {"ExtUserPtr":{"__type":"Pointer","className":"contracts_Users","objectId":"PJbvhSBP7G"},"CreatedBy":{"__type":"Pointer","className":"_User","objectId":"Fa5iA4nN6b"},"URL":"http://127.0.0.1:8080/app/files/opensignstgn/6ee3f92c93d4c44c47a44e7f38547fac_Cartell_EsmorzArt.pdf","Name":"sdfdsf","IsCompleted":false,"IsDeclined":false,"SendinOrder":false,"RemindOnceInEvery":5,"AutomaticReminders":false,"SentToOthers":false,"TimeToCompleteDays":15,"createdAt":"2023-11-06T19:49:27.300Z","updatedAt":"2023-11-06T19:49:27.341Z","ACL":{"Fa5iA4nN6b":{"read":true,"write":true},"*":{"read":true,"write":true}},"ExpiryDate":{"__type":"Date","iso":"2023-11-21T19:49:27.300Z"},"objectId":"GrYY3YINBR"}
OpenSignServer-container  |   Result: undefined {"className":"contracts_Document","triggerType":"afterSave"}
OpenSignServer-container  | info: afterSave triggered for contracts_Document for user Fa5iA4nN6b:
OpenSignServer-container  |   Input: {"ACL":{"Fa5iA4nN6b":{"read":true,"write":true},"*":{"read":true,"write":true}},"ExtUserPtr":{"__type":"Pointer","className":"contracts_Users","objectId":"PJbvhSBP7G"},"CreatedBy":{"__type":"Pointer","className":"_User","objectId":"Fa5iA4nN6b"},"URL":"http://127.0.0.1:8080/app/files/opensignstgn/6ee3f92c93d4c44c47a44e7f38547fac_Cartell_EsmorzArt.pdf","Name":"sdfdsf","createdAt":"2023-11-06T19:49:27.300Z","IsCompleted":false,"IsDeclined":false,"SendinOrder":false,"RemindOnceInEvery":5,"AutomaticReminders":false,"SentToOthers":false,"TimeToCompleteDays":15,"updatedAt":"2023-11-06T19:49:27.300Z","objectId":"GrYY3YINBR"}
OpenSignServer-container  |   Result: undefined {"className":"contracts_Document","triggerType":"afterSave","user":"Fa5iA4nN6b"}
OpenSignServer-container  | info: afterSave triggered for contracts_Document for user undefined:
OpenSignServer-container  |   Input: {"ExtUserPtr":{"__type":"Pointer","className":"contracts_Users","objectId":"PJbvhSBP7G"},"CreatedBy":{"__type":"Pointer","className":"_User","objectId":"Fa5iA4nN6b"},"URL":"http://127.0.0.1:8080/app/files/opensignstgn/6ee3f92c93d4c44c47a44e7f38547fac_Cartell_EsmorzArt.pdf","Name":"sdfdsf","IsCompleted":false,"IsDeclined":false,"SendinOrder":false,"RemindOnceInEvery":5,"AutomaticReminders":false,"SentToOthers":false,"TimeToCompleteDays":15,"createdAt":"2023-11-06T19:49:27.300Z","updatedAt":"2023-11-06T19:49:27.386Z","ExpiryDate":{"__type":"Date","iso":"2023-11-21T19:49:27.300Z"},"ACL":{"Fa5iA4nN6b":{"read":true,"write":true}},"objectId":"GrYY3YINBR"} {"className":"contracts_Document","triggerType":"afterSave"}
OpenSignServer-container  | info: afterSave triggered for contracts_Document for user undefined:
OpenSignServer-container  |   Input: {"ExtUserPtr":{"__type":"Pointer","className":"contracts_Users","objectId":"PJbvhSBP7G"},"CreatedBy":{"__type":"Pointer","className":"_User","objectId":"Fa5iA4nN6b"},"URL":"http://127.0.0.1:8080/app/files/opensignstgn/6ee3f92c93d4c44c47a44e7f38547fac_Cartell_EsmorzArt.pdf","Name":"sdfdsf","IsCompleted":false,"IsDeclined":false,"SendinOrder":false,"RemindOnceInEvery":5,"AutomaticReminders":false,"SentToOthers":false,"TimeToCompleteDays":15,"createdAt":"2023-11-06T19:49:27.300Z","updatedAt":"2023-11-06T19:49:27.386Z","ExpiryDate":{"__type":"Date","iso":"2023-11-21T19:49:27.300Z"},"ACL":{"Fa5iA4nN6b":{"read":true,"write":true}},"objectId":"GrYY3YINBR"}
OpenSignServer-container  |   Result: undefined {"className":"contracts_Document","triggerType":"afterSave"}
```

**Comment by rishabjasrotia** [comment]
Hello @maoo 
I know the reason for this issue is due to missing build files.

You need to build the package in microfrontends.

Command to do this:
````
cd microfrontends/SignDocuments && npm install && npm run build
````

You should get the public files ready in `/microfrontends/SignDocuments/public`

Note: In case public files are created and move command fails then you should manually copy files from `/microfrontends/SignDocuments/public` to `/apps/OpenSign/public/mfbuild`


Note: You also need to delete the old docker images and container so it rebuilds with **mfbuild** files


cc @andrew-opensignlabs

**Comment by maoo** [comment]
Thank you @rishabjasrotia !

I got it working following your instructions; just a couple of notes:
- the `apps/OpenSign/public/mfbuild` folder already exists, so the `mv`/`cp` commands would fail
- the `npm run build` command in `microfrontends/SignDocuments` already moves the `mfbuild` folder across

For reference, this is the list of actions that leads to a successful (docker) local run:
```
rm -rf apps/OpenSign/public/mfbuild
cd microfrontends/SignDocuments && npm install && npm run build
docker compose up -d
```

I'd be happy to work on the fix, though I'm not sure what's the best practice for packaging microfrontends into Docker images.

As you may know, Dockerfiles have issues accessing files that are not located under its folder; moving the `microfrontends` folder under `apps/OpenSign` (or moving `apps/OpenSign/Dockerfile` in the root folder, maybe calling it `Dockerfile.app`) would solve the issue, but it may not be the best approach.

**Comment by saketoz98** [comment]
I am getting the same error while submitting the document. I have followed the "Frontend Only" approach for installation.

**Comment by rishabjasrotia** [comment]
We can close this issue PR merged
#162
