### ISSUE TITLE
Upgrade to v1.4.2 failed

### ISSUE THREAD

**Issue by sherlant** [OpenSignLabs/OpenSign#559]
Hi,
i have try to upgrade my opensign instance from v1.2.2-beta to v1.4.2.
After the upgrade, i've try to retrieve my password my the forgot password button, but when i submit with my email, a popup tell me that i must configure an email adapter.
I have already setup SMTP configuration, and the configuration was OK in v1.2.2-beta.
In the new documentation, i don't see SMTP configuration, only with MAILGUN_API_KEY/MAILGUN_DOMAIN/MAILGUN_SENDER, i have try to modify my configuration with this env vars, same result.
I have try to create a new user too, and i have an other error when i submit the form :
```
XMLHttpRequest failed: "SyntaxError: Unexpected token '<', \"<!doctype \"... is not valid JSON"
```
Can you help me please ?

**Comment by sherlant** [comment]
Hello,
this issue still with v1.5.1.

Any update ?

**Comment by nxglabs** [comment]
Can you share the opensign-server logs when you encounter this error?

**Comment by sherlant** [comment]
sorry, there are nothing in logs when i have the error in web ui. The only logs are in the server starting :
```

> open_sign_server@1.4.0 start
> node index.js

(node:21) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
(node:21) NOTE: The AWS SDK for JavaScript (v2) will enter maintenance mode
on September 8, 2024 and reach end-of-support on September 8, 2025.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check blog post at https://a.co/cUPnyil
parse-server-example running on port 8080.
Command output: 
Parse DBTool v1.2.0 - Parse server tool for data migration and seeding.

Run migration on parse-server at http://localhost:8080/app

 ⠶ Migrating 20240408133151-update_contracts_document_cls.cjs
 ✓ Migrated  20240408133151-update_contracts_document_cls.cjs


 SUCCESS  Successfully run migrations.
```

**Comment by sherlant** [comment]
Hi,
i have try to deploy opensign in latest version (v1.7.2) from scratch.
After the deploy, i find two issues :
- The logs in opensign-server at start :
```

> open_sign_server@1.4.0 start
> node index.js

(node:21) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
(node:21) NOTE: The AWS SDK for JavaScript (v2) will enter maintenance mode
on September 8, 2024 and reach end-of-support on September 8, 2025.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check blog post at https://a.co/cUPnyil
parse-server-example running on port 8080.

WARNING, Unable to connect to 'http://localhost:8080/app'. Cloud code and push notifications may be unavailable!

Error: Command failed: APPLICATION_ID=XXXXXXX SERVER_URL=http://localhost:8080/app MASTER_KEY=XXXXXXX npx parse-dbtool migrate
parse-dbtool migrate

Run migrations

Options:
      --version  Show version number                                   [boolean]
  -h, --help     Show help                                             [boolean]

ParseError: XMLHttpRequest failed: "Unable to connect to the Parse API"
    at handleError (/usr/src/app/node_modules/parse-dbtool/node_modules/parse/lib/node/RESTController.js:425:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async /usr/src/app/node_modules/parse-dbtool/node_modules/parse/lib/node/ParseQuery.js:1177:25
    at async ParseQuery.findAll (/usr/src/app/node_modules/parse-dbtool/node_modules/parse/lib/node/ParseQuery.js:853:5)
    at async getAllRunMigrations (/usr/src/app/node_modules/parse-dbtool/src/libs/migration-model.js:38:22)
    at async getAllMigrations (/usr/src/app/node_modules/parse-dbtool/src/libs/migration-model.js:69:28)
    at async migrationUp (/usr/src/app/node_modules/parse-dbtool/src/migration-up.js:38:27)
    at async Object.migrationUpHandler [as handler] (/usr/src/app/node_modules/parse-dbtool/src/migration-up.js:85:25) {
  code: 100
}
```
- in the ui, when i try to create a new account, i have the same error :
```
XMLHttpRequest failed: "SyntaxError: Unexpected token '<', \"<!doctype \"... is not valid JSON"
```

**Comment by Zathiel** [comment]
Hey @sherlant 

Are you still facing issues with the last release ?

If not i will mark this issue as solved

**Comment by dgilsonAfelio** [comment]
I got the exact same issue
